### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by jonathanzhang99** [stanford-futuredata/loa#1]
I believe this package is missing a `setup.py` or `requirements.txt` in order to install dependencies. Let me know if I'm missing something!

**Comment by ddkang** [comment]
Should have pushed these now!

**Comment by jonathanzhang99** [comment]
Thank you for the update however the install still does not work :( I am using standard python3.9 and pip (non-conda) and running `pip install -e .` does not install the dependencies. Similarly, `pip install -r requirements.txt` throws
```
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/System/Volumes/Data/home/ktietz/src/ci/alabaster_1611921544520/work'
```
Could you offer any help?
