### ISSUE TITLE
Missing predictions from `preds.p`

### ISSUE THREAD

**Issue by jonathanzhang99** [stanford-futuredata/loa#3]
Do you have a reference to the model predictions (or model parameters) that you used and serialized in `preds.p`. Or if you can't share that information, as much detail as possible about the model that you used, accuracy of the prediction model, and format of the prediction output file (`preds.p`)? It is currently hard to run the code/duplicate your results without those model predictions.

**Comment by jonathanzhang99** [comment]
found in repo - sorry about that! (although might be better to use absolute paths in the future)

**Comment by ddkang** [comment]
We used this model (which we trained at the time of writing - I believe it may have been updated in the meantime): https://github.com/poodarchu/Det3D.git
